TaskApp/tasks/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField, SubmitField, SelectField,DateTimeLocalField
from wtforms.validators import DataRequired

#Form for task created to be used in html to get values and add to models
class TaskForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    description = TextAreaField("Description", validators=[DataRequired()])
    due_date = DateTimeLocalField("Due Date", validators=[DataRequired()], format='%Y-%m-%dT%H:%M')
    importance = SelectField("Importance", choices=[('Not really important', 'Not really important'), ('Important', 'Important'), ('Very Important', 'Very Important')], coerce=str, validators=[DataRequired()])
    complexity = SelectField("Complexity", choices=[('Easy', 'Easy'), ('Ok', 'Ok'), ('Very Complex', 'Very Complex')], coerce=str, validators=[DataRequired()])
    submit=SubmitField("Submit")

TaskApp/main/routes.py
from flask import Blueprint, render_template
from flask_login import current_user

main = Blueprint('main', __name__)

# Home route
@main.route('/')
@main.route('/home')
def home():
    # Display welcome (username) if user is logged in
    if current_user.is_authenticated:
        username = current_user.username
        return render_template('home.html', title="TASKINGENIUM", username=username)
    else:
        return render_template('home.html', title="TASKINGENIUM")

TaskApp/tasks/__init__.py
#Tasks Package

TaskApp/tasks/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, abort, request, jsonify, current_app
from TaskApp import db
from TaskApp.tasks.forms import TaskForm
from flask_login import login_required, current_user
from TaskApp.models import Task
from datetime import datetime
import secrets
from TaskApp.tasks.utils import send_task_notification,delete_expired_tasks

tasks=Blueprint('tasks', __name__)


# Task list route: Display all users tasks just title and small description not all and sort by due_date
@tasks.route("/tasks")
@login_required
def task_list():
    tasks = Task.query.filter_by(user_id=current_user.id)
    tasks=tasks.filter(Task.due_date > datetime.now() ).filter( Task.completed == False).order_by(Task.due_date).all()

    formatted_tasks = [{'title': task.title,
                        'due_date': task.due_date,
                        "task_secret":task.task_secret,
                        "importance": task.importance,
                        'complexity':task.complexity
                        } for task in tasks]
    return render_template("tasks.html", tasks=formatted_tasks, title="Task List")

# New route to get tasks for a specific view (e.g., "tasks", "expired", "completed")
@tasks.route("/tasks/<view>")
@login_required
def get_tasks_by_view(view):
    if view == "expired":
        # Delete expired tasks before fetching the tasks to display
        delete_expired_tasks()
        
    task = Task.query.filter_by(task_secret=view).first()
    if task:
        formatted_task = {'title': task.title,
                        'description': task.description,
                        'importance': task.importance,
                        'due_date': task.due_date.strftime('%Y-%m-%d %H:%M'),
                        "task_secret":task.task_secret,
                        'complexity':task.complexity
                        }
        return render_template('task.html', task=formatted_task, title="Task")
    
    tasks_query = Task.query.filter_by(user_id=current_user.id)

    if view == "expired":
        tasks_query = tasks_query.filter(Task.due_date < datetime.now()).filter(Task.completed != True)
    elif view == "completed":
        tasks_query = tasks_query.filter(Task.completed == True)
    
    tasks = tasks_query.order_by(Task.due_date.desc()).all()

    formatted_tasks = [{'title': task.title,
                        'due_date': task.due_date,
                        'task_secret': task.task_secret,
                        'importance': task.importance,
                        'complexity':task.complexity
                        } for task in tasks]

    return render_template("tasks.html", tasks=formatted_tasks, title="Task List")

# Route to handle checkbox and completed tasks
@tasks.route("/tasks/complete/<task_secret>", methods=["POST"])
@login_required
def complete_task(task_secret):
    task = Task.query.filter_by(task_secret=task_secret, user_id=current_user.id).first_or_404()

    # Toggle the 'completed' field
    task.completed = not task.completed
    
    db.session.commit()
    
    return redirect(url_for('tasks.task_list'))

# Route to display the specific task and the information retated to it
@tasks.route('/tasks/<task_secret>')
@login_required
def task(task_secret):
    task = Task.query.filter_by(task_secret=task_secret).first()
    
    formatted_task = {'title': task.title,
                      'description': task.description,
                      'importance': task.importance,
                      'due_date': task.due_date.strftime('%Y-%m-%d %H:%M'),
                      "task_secret":task.task_secret ,
                      'complexity':task.complexity
                      }
    return render_template('task.html', task=formatted_task, title="Task")

#Route to create task and add it to the form then the database
@tasks.route("/tasks/create_task", methods=["GET","POST"])
@login_required
def create_task():
    secret=secrets.token_hex(20)
    form=TaskForm()
    if form.validate_on_submit():
        task=Task(title=form.title.data,
                  description=form.description.data,
                  due_date=form.due_date.data,
                  importance=form.importance.data,
                  user_id=current_user.id,
                  task_secret= secret,
                  completed=False,
                  complexity=form.complexity.data
                  )
        db.session.add(task)
        db.session.commit()
        send_task_notification("Task Created",
                                f"Your task {form.title.data} has been created.",
                                form.title.data,
                                    secret)
        return redirect(url_for("tasks.task_list")) 
    return render_template("create_task.html", title="New Task", legend="New Task", form=form)

#Route to update tasks
@tasks.route("/task/<task_secret>/update_task", methods=["GET","POST"])
@login_required
def update_task(task_secret):
    task=Task.query.filter_by(task_secret=task_secret).first_or_404()
    if task.user_id != current_user.id:
        abort(403)
    form=TaskForm()
    if form.validate_on_submit():
        task.title=form.title.data
        task.description=form.description.data
        task.due_date= form.due_date.data
        task.importance=form.importance.data
        task.complexity=form.complexity.data
        db.session.add(task)
        db.session.commit()
        flash('Your Task Has Been Updated', 'success')
        return redirect(url_for("tasks.task_list", user_id=current_user.id))
    elif request.method == 'GET':
        form.title.data=task.title
        form.due_date.data=task.due_date
        form.description.data=task.description
        form.importance.data=task.importance
        form.complexity.data=task.complexity

    return render_template("create_task.html", title="Update Task", legend="New Task", form=form)

# Route to handle function to delete task
@tasks.route("/task/<task_secret>/delete")
@login_required
def delete_task(task_secret):
    task=Task.query.filter_by(task_secret=task_secret).first_or_404()
    if task.user_id != current_user.id:
        abort(403)
    db.session.delete(task)
    db.session.commit()
    flash('Your Task Has Been Deleted', 'success')
    return redirect(url_for("tasks.task_list"))

TaskApp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from TaskApp import db, bcrypt
from TaskApp.models import User,Task
from TaskApp.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from TaskApp.users.utils import send_reset_email
from sqlalchemy import text

users=Blueprint('users', __name__)

#The user signup route
@users.route("/signup", methods=['GET','POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=RegistrationForm()
    if form.validate_on_submit():
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user=User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your Account has been Created! You are now able to  Login ', 'success')
        return redirect(url_for('users.login'))
    return render_template('signup.html', title='Signup',form=form)

#The user login route
@users.route("/login",methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=LoginForm()
    if form.validate_on_submit():
       user=User.query.filter_by(email=form.email.data).first()
       if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember= form.remember.data)
            next_page=request.args.get('next')
            return redirect(next_page) if next_page else  redirect(url_for('main.home'))
       else:
        flash("Login Unsuccessful. Please Check Username And Password","danger")
    return render_template('login.html', title='Login',form=form)

#The user logout route
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

#The user account route
@users.route("/account", methods=['GET','POST'])
@login_required
def account():
     form=UpdateAccountForm()
     if form.validate_on_submit():

         current_user.username= form.username.data
         current_user.email = form.email.data
         db.session.commit()
         flash('Your Account Has Been Updated!', 'success')
         return redirect(url_for('users.account'))
     
     elif request.method== 'GET':
         form.username.data= current_user.username
         form.email.data = current_user.email
        
     return render_template('account.html', title='Account',
                              form=form)

#The user reset passowrd route
@users.route("/reset_password",methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=RequestResetForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("Your Email has been sent with instructions to reset your password", 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

#The secret reset password route
@users.route("/reset_password/<token>",methods=['GET','POST'])
def reset_token(token):
     if current_user.is_authenticated:
        return redirect(url_for('main.home'))
     user= User.verify_reset_token(token)
     if user is None:
         flash('That is an Invalid or Expired Token', 'warning')
         return redirect(url_for('users.reset_request'))
     form= ResetPasswordForm()
     if form.validate_on_submit():
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password=hashed_password
        db.session.commit()
        flash('Your Password has been updated! You are now able to  Login ', 'success')
        return redirect(url_for('users.login'))
     return render_template('reset_token.html', title='Reset Password', form=form)

#Delete user account route     
@users.route('/delete_account', methods=['GET', 'POST'])
@login_required
def delete_account():
    if request.method == 'POST':
        user = current_user
        task=Task.query.filter_by(user_id=current_user.id)
        for t in task:
            db.session.delete(t)
        db.session.delete(user)
        db.session.commit()
        with db.engine.connect() as connection:
            connection.execute(text("VACUUM"))
        
        db.session.commit()
        

        flash('Your account has been deleted.', 'success')
        return redirect(url_for('users.logout'))

 
    return redirect(url_for('main.home'))

TaskApp/templates/account.html
{% extends "layout.html" %}
{% block content %}
<!-- The main div section to display the users current email and name -->
<div class="content-section">
    <div class="media">
     <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
      </div>
    </div>
        <!-- The form field container -->
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>

                <!-- The username update form -->
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <!-- The password update form -->
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                
            </fieldset>
            <!-- Submit button -->
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>

        
<!--  Delete account form -->
<h2 class="DeleteAccount">Delete Account</h2>

<form method="POST", action="/delete_account" id="delete-account-form">
    <button type="button" onclick="confirmDelete()" >Delete Account</button>
</form>
<input type="hidden" id="user-username" value="{{ current_user.username }}">
  </div>
  <script>
    function confirmDelete() {
const username = document.getElementById('user-username').value; // Get the user's username
if (confirm(`Are you sure you want to delete your account with username: "${username}"?`)) {
    // If the user clicks "OK" in the confirmation dialog, the form will be submitted.
    document.querySelector('#delete-account-form').submit();
} else {
    // If the user clicks "Cancel" in the confirmation dialog, nothing happens.
}
}
</script>
{% endblock content %}

TaskApp/templates/create_task.html
{% extends "layout.html" %}
{% block content %}
<!-- Main div container to create task -->
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>

            <!-- The title form field -->
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <!-- The description form field -->
            <div class="form-group">
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                    {{ form.description(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.description.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.description(class="form-control form-control-lg") }}
                {% endif %}
                </div>
                
                <!-- The due_date form field -->
                <div class="form-group">
                    {{ form.due_date.label(class="form-control-label") }}
                    {% if form.due_date.errors %}
                        {{ form.due_date(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.due_date.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.due_date(class="form-control form-control-lg",type="datetime-local") }}
                    {% endif %}
                    </div>
                    <!-- The importance form field -->
                    <div class="form-group">
                        {{ form.importance.label(class="form-control-label") }}
                        {% if form.importance.errors %}
                            {{ form.importance(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.importance.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.importance(class="form-control form-control-lg", id="importance") }}
                        {% endif %}
                    </div>

                    <!-- The complexity form field -->
                    <div class="form-group">
                        {{ form.complexity.label(class="form-control-label") }}
                        {% if form.complexity.errors %}
                            {{ form.complexity(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.complexity.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.complexity(class="form-control form-control-lg", id="complexity") }}
                        {% endif %}
                    </div>
                    
                    

            </fieldset>
            <!-- Submit button -->
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

TaskApp/templates/home.html
{% extends "layout.html" %}
{% block content %}


<!-- Welcome message -->
<h4>{% if current_user.is_authenticated %}
    Welcome, {{ username }}!
{% endif %} </h4>


<!-- Short Writeup for homepage -->
<article>

    <p>TaskIngenium is a powerful task management application 
        designed to enhance productivity and streamline the organization 
        of daily responsibilities.TaskIngenium goes beyond traditional task managers by offering intelligent task prioritization based on user behavior. 
        The application empowers users to create, prioritize, 
        and track tasks efficiently, ensuring that the most 
        crucial activities are readily identified and addressed. 
        With a user-friendly web interface, 
        TaskIngenium provides a visually intuitive experience, 
        making task management a seamless and enjoyable process.</p>

        <p>The usefulness of TaskIngenium lies in its ability to adapt to individual user preferences and work patterns.
             The machine learning component analyzes historical task completion data, 
             allowing the application to learn and predict task priorities tailored to each user's unique needs. 
             This personalized approach not only saves time but also optimizes decision-making, ensuring that users focus on tasks that align with their goals and deadlines. 
             TaskIngenium serves as a reliable ally for individuals and teams, transforming the often overwhelming realm of task management into a more manageable, strategic, 
             and ultimately rewarding experience.</p>
</article>

{% endblock content %}

TaskApp/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="shortcut icon" href="/static/favicon.ico" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <!-- Bootstrap css -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{{ title }}</title>
</head>

<body>

    <!-- Navigation bar -->
    <nav style="text-align: center;">
        <h1 > {{ title }} </h1>
        <ul>
            {% if current_user.is_authenticated %}
            <li>
                <a href="{{ url_for('main.home')}}">Home </a>
            </li>

            <li>
                <a href="{{ url_for('users.account')}}">Account </a>
            </li>

            <li>
                <a href="{{ url_for('tasks.task_list')}}">Tasks</a>
            </li>

            <li>
                <a href="{{ url_for('users.logout')}}">Logout </a>
            </li>

            {% else %}
            <li>
                <a href="{{ url_for('main.home')}}">Home </a>
            </li>
            <li>
                <a href="{{ url_for('users.signup')}}">Signup </a>
            </li>
            <li>
                <a href="{{ url_for('users.login')}}">Login </a>
            </li>
            {% endif %}
        </ul>
    </nav>

    <!-- Flashed messages -->
    <section class="main-content">
        {% with messages= get_flashed_messages(with_categories=True) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}

        {% block content %}
        <!-- Block content section where all HTML is linked to the layout -->
        {% endblock %}
    </section>

    <footer>
        <div>
            <h5>TaskIngenium</h5>
            <p>Contact us: +234 9125090790</p>
            <p><a href="mailto:michael.c.ezeana@gmail.com" class="external-links">michael.c.ezeana@gmail.com</a></p>
        </div>
    </footer>

    <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

TaskApp/templates/login.html
{% extends "layout.html" %}
{% block content %}

<!-- The div for the form -->
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login</legend>

            <!-- The Email validation form -->
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <!-- The password validation form -->
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <!--  Remember me form, so users don't need to login everytime -->
            <div class="form-check">
                {{ form.remember(class="form-check-input")}}
                {{ form.remember.label(class="form-check-label")}}

            </div>
           
            
        </fieldset>
        <!-- Submit button -->
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
            
        </div>
        <!-- Forgot password link -->
        <div class="form-group">
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request')}}">Forgot Password?</a>
            </small>
        </div>
        <!-- Signup link -->
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{{ url_for('users.signup') }}">Sign Up Now</a>
            </small>
        </div>
    </form>
</div>

{% endblock content %}

TaskApp/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
<!-- Password reset request form -->

<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>

            <!-- Email form -->
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            
        </fieldset>
        <!-- Submit button -->
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        
    </form>
</div>

{% endblock content %}

TaskApp/templates/task.html
{% extends "layout.html" %}
{% block content %}
<!-- Displaying the task and information related to it -->
<div class="content-section">
    <h2>{{ task.title }}</h2>
    <p>Current time :<span id="datetime"></span> </p>
    <p>{{ task.description }}</p>
    <p><strong>Importance:</strong> {{ task.importance }}</p>
    <p><strong>Due Date:</strong>{{ task.due_date }}</p>
    <p ><strong>Complexity: </strong> {{ task.complexity }}</p>

    <!-- Update task button -->
<a href="{{ url_for('tasks.update_task', task_secret=task.task_secret) }}" class="btn btn-primary">Update Task</a>
        
<!-- Delete task button -->
<a href="{{ url_for('tasks.delete_task', task_secret=task.task_secret) }}" class="btn btn-primary">Delete Task</a>
   
</div>

<script src="{{ url_for('static', filename='js/main.js') }}"></script>

{% endblock content %}

TaskApp/templates/tasks.html
{% extends "layout.html" %}

{% block content %}
<div class="app">
    <div class="menu-toggle" onclick="toggleSidebar()">
        <div class="hamburger">
            <span></span>
        </div>
    </div>

    <aside class="sidebar">
        <div class="navigation">
            <a href="/tasks" id="tasksLink" onclick="showTasks()">Tasks</a>
            <a href="/tasks/expired" id="expiredTasksLink" onclick="showExpiredTasks()">Expired Tasks</a>
            <a href="/tasks/completed" id="completedTasksLink" onclick="showCompletedTasks()">Completed Tasks</a>
        </div>
    </aside>

    <main class="content-section">
       
       
        <h2>Your Tasks</h2>
    
        <!-- Current time -->
        <p>Current time :<span id="datetime"></span> </p>
    
        <!-- No task created -->
        {% if tasks==[] %}
            <p>No tasks created yet</p>
            <!-- Button to create new task -->
            <a href="{{ url_for('tasks.create_task') }}" class="btn btn-primary">Create New Task</a>
        {% else %}
            <!-- Lists of users task -->
            <ol>
                {% for task in tasks %}
                    <li>
                        <article class="tasklist">
                            <div id="taskContainer">
                                <h3><a href="{{ url_for('tasks.task', task_secret=task.task_secret) }}" class="task-title">{{ task.title }}</a></h3>
                                <label>Completed
                                    <input type="checkbox" class="checkbox" data-task-secret="{{ task.task_secret }}">
                                </label>
                                <p class="task-due_date"> Due Date : {{ task.due_date }}</p>
                                <p class="task-importance">Importance : {{ task.importance }}</p>
                                <p class="task-complexity">Complexity : {{ task.complexity }}</p>
                            </div>
                        </article>
                    </li>  
                {% endfor %}
            </ol>
            <a href="{{ url_for('tasks.create_task') }}" class="btn btn-primary">Create New Task</a>
        {% endif %}
    </main>
</div>


    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
{% endblock content %}